version: '3.1'

services:

  db:
    image: 'mysql:8.0.18'
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: default
    ports:
      - 13306:3306
    volumes:
      - mysql-volume:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8000:8080

volumes:
  mysql-volume:
